### PR TITLE
Fix dashboard errors on installation

### PR DESCRIPTION
**Pull request by idoqo**
This includes a couple of changes around fixing the dashboard and improving installation (yet again haha).

Some of them include:
- Option to install a dev version of Spinup. This requires `go` to be installed on the system, and users can choose a specific branch (or release to install).
- Fix dashboard returning 404 errors as we now use [chi router](https://github.com/go-chi/chi/) for dashboard routes. See https://create-react-app.dev/docs/deployment/#serving-apps-with-client-side-routing
- We now return the same response format for all endpoints that return cluster-info (list and create).

### CODE REVIEW

**Review by skant7 — APPROVED** [review]

**Review by viggy28 — APPROVED** [review]

**Comment by viggy28** [comment]
so how do the end-users install?

**Comment by viggy28** [comment]
getting 
```
2022/04/22 22:38:58 ERROR: starting new docker service for testuser unable to start container for image amd64/postgres:13.0: Error response from daemon: network spinup_services not found
```

**Comment by idoqo** [comment]
> so how do the end-users install?

The existing installation method in the readme still works fine (and they don't have to install go since it uses the release binaries). Will take a closer look at the error to see.

**Comment by viggy28** [comment]
Looks like the existing script is completely removed.

**Comment by idoqo** [comment]
> Looks like the existing script is completely removed.

I see it now - somehow, the file mode changed so github marked it as "empty change". I've reverted now though, and the network now gets created on startup as well.

**Review by akshat2602 — APPROVED** [review]

**Review by viggy28 — APPROVED** [review]

**Comment by viggy28** [comment]
thanks @idoqo . LGTM.

**Pull request merged**
